In [1]:
import pandas as pd
import tweepy
import time
import json
import matplotlib.pyplot as plt
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [2]:
consumer_key = "c6dgM5QsWgeCohFBph3KYMoEg"
consumer_secret = "DeeARxOWob5QNDtB0naVuoOJzUAPiYVakwLqT3gdCFVqHBkEd6"
access_token = "2877438220-pzB64pnJWU6Y7eL03rM94ho0pQ5uSmwiXMY9aEn"
access_token_secret = "G4pijrgYjA0WyH3cMhy85Y3LE2qob04kTnzBfWj8gdDMy"

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, parser=tweepy.parsers.JSONParser())

In [4]:
target_users = ["BBC", "CBS", "CNN", "Fox"]


df = pd.DataFrame(columns= ["Counter", "User", "News", "Negative", "Positive", "Neutral" , "Compound"])




for i in target_users:
    counter = 0
    target_user = i
    
    for x in range(5):

        public_tweets = api.user_timeline(target_user)
        
        
        for j in public_tweets:

            text = j["text"]
            
            x = analyzer.polarity_scores(text)
            
            Negative = x["neg"]
            Positive  = x["pos"]
            Neutral = x["neu"]
            Compound = x["compound"]
            
            counter +=1
            
            
            df2 = pd.DataFrame([[counter, i, text, Negative, Positive, Neutral , Compound]], 
                               columns= ["counter","user", "news","Negative","Positive","Neutral","Compound"])
            
            
            
            df = df.append(df2)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [5]:
df.to_csv("news.csv",encoding="utf-8", index=False)

In [10]:
df.head(3)

,Compound,Counter,Negative,Neutral,News,Positive,User,counter,news,user
0,0.0000,NaN,0.000,1.000,NaN,0.000,NaN,1.0,"üèÉüí™ @LesDennis, @SimplySusannah, @Tameka_Empson...",BBC
0,0.0258,NaN,0.086,0.824,NaN,0.090,NaN,2.0,üëéüíå Fans of K-Pop boyband member @IBGDRGN have ...,BBC
0,0.5994,NaN,0.000,0.803,NaN,0.197,NaN,3.0,"Saoirse Ronan stars as Eilis, a young girl who...",BBC

In [1]:

plt.scatter(df["counter"], df["Compound"], marker="o", facecolors="blue", alpha = 0.90, label = df["user"])


plt.title("Sentiment Analysis")
plt.xlabel("Tweets Ago")
plt.ylabel("Compound Score")

NameError: name 'plt' is not defined

In [2]:
plt.show()

NameError: name 'plt' is not defined